language: node_js

node_js:
  - 'stable'

cache:
  directories:
    - ~/mycache
    - node_modules
    - dist

jobs:
  include:
    - stage: build
      before_install: rm -rf dist
      script: yarn build
    - stage: deploy to GH pages
      if: (branch = master)
      install: true
      script:
        - openssl aes-256-cbc -K $encrypted_3e928e27b2f9_key -iv $encrypted_3e928e27b2f9_iv -in github_deploy_key.enc -out ~/.ssh/id_rsa -d
        - chmod 400 ~/.ssh/id_rsa
        - cd dist
        - git init
        - git remote add origin git@github.com:visualstorytelling/provenance-tree-calculator-demo.git
        - git pull origin gh-pages && git checkout gh-pages
        - git commit -a -m "travis deploy"
        - git push origin gh-pages